name: Main

on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - name: npm install
      run: npm install
    - name: npm test
      run: npm test
    - name: abaplint --version
      run: ./packages/cli/abaplint --version
    - name: npm run web.rules
      run: npm run web.rules
    - name: deploy schema.abaplint.org
      if: github.ref == 'refs/heads/master' && github.repository == 'abaplint/abaplint'
      env:
        MY_TOKEN: ${{ secrets.MY_TOKEN }}
      run: |
        cd ..
        cd ..
        git config --global user.email "actions@github.com"
        git config --global user.name "Actions CI"
        git clone https://github.com/abaplint/schema.abaplint.org.git
        ls
        cp abaplint/abaplint/packages/core/scripts/schema.json schema.abaplint.org/schema.json
        PACKAGE_VERSION=$(node -p -e "require('./abaplint/abaplint/packages/core/package.json').version")
        cp -n abaplint/abaplint/packages/core/scripts/schema.json schema.abaplint.org/schema-${PACKAGE_VERSION}.json
        cd schema.abaplint.org
        git add -A
        git status
        git diff-index --quiet HEAD || git commit -m "Automatic update"
        git push -q https://$MY_TOKEN@github.com/abaplint/schema.abaplint.org.git > /dev/null 2>&1
    - name: deploy rules.abaplint.org
      if: github.ref == 'refs/heads/master' && github.repository == 'abaplint/abaplint'
      env:
        MY_TOKEN: ${{ secrets.MY_TOKEN }}
      run: |
        cd ..
        cd ..
        git config --global user.email "actions@github.com"
        git config --global user.name "Actions CI"
        git clone https://github.com/abaplint/rules.abaplint.org.git
        ls
        cp -r abaplint/abaplint/web/rules/build/* rules.abaplint.org/
        cd rules.abaplint.org
        git add -A
        git status
        git diff-index --quiet HEAD || git commit -m "Automatic update"
        git push -q https://$MY_TOKEN@github.com/abaplint/rules.abaplint.org.git > /dev/null 2>&1
