name: Main

on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install
      run: npm install
    - name: npm test
      run: npm test
    - name: abaplint --version
      run: |
        ls
        ./packages/cli/abaplint --version
    - name: npm run web.syntax
      run: npm run web.syntax
    - name: deploy schema.abaplint.org
      if: github.ref == 'refs/heads/master' && github.repository == 'abaplint/abaplint'
      env:
        MY_TOKEN: ${{ secrets.MY_TOKEN }}
      run: |
        cd ..
        cd ..
        git config --global user.email "actions@github.com"
        git config --global user.name "Actions CI"
        git clone https://github.com/abaplint/schema.abaplint.org.git
        ls
        cp abaplint/abaplint/packages/core/scripts/schema.json schema.abaplint.org/schema.json
        cd schema.abaplint.org
        git add -A
        git status
        git diff-index --quiet HEAD || git commit -m "Automatic update"
        git push -q https://$MY_TOKEN@github.com/abaplint/schema.abaplint.org.git > /dev/null 2>&1
    - name: deploy syntax.abaplint.org
      if: github.ref == 'refs/heads/master' && github.repository == 'abaplint/abaplint'
      env:
        MY_TOKEN: ${{ secrets.MY_TOKEN }}
      run: |
        cd ..
        cd ..
        git config --global user.email "actions@github.com"
        git config --global user.name "Actions CI"
        git clone https://github.com/abaplint/syntax.abaplint.org.git
        ls
        cp abaplint/abaplint/web/syntax/* syntax.abaplint.org/
        cd syntax.abaplint.org
        git add -A
        git status
        git diff-index --quiet HEAD || git commit -m "Automatic update"
        git push -q https://$MY_TOKEN@github.com/abaplint/syntax.abaplint.org.git > /dev/null 2>&1
