name: Main

on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - name: npm install
      run: npm install
    - name: npm test
      run: npm test
    - name: abaplint --version
      run: ./packages/cli/abaplint --version
    - name: npm run web.rules
      run: npm run web.rules
    - name: prepare schema.abaplint.org
      run: |
        cd ..
        cd ..
        git clone https://github.com/abaplint/schema.abaplint.org.git
        ls
        cp abaplint/abaplint/packages/core/scripts/schema.json schema.abaplint.org/schema.json
        PACKAGE_VERSION=$(node -p -e "require('./abaplint/abaplint/packages/core/package.json').version")
        cp -n abaplint/abaplint/packages/core/scripts/schema.json schema.abaplint.org/schema-${PACKAGE_VERSION}.json
    - name: deploy schema.abaplint.org
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' && github.repository == 'abaplint/abaplint'
      with:
        deploy_key: ${{ secrets.SCHEMA_DEPLOY_KEY }}
        external_repository: abaplint/schema.abaplint.org
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        publish_branch: main
        cname: schema.abaplint.org
        publish_dir: ../../schema.abaplint.org
    - name: deploy rules.abaplint.org
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' && github.repository == 'abaplint/abaplint'
      with:
        deploy_key: ${{ secrets.RULES_DEPLOY_KEY }}
        external_repository: abaplint/rules.abaplint.org
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        publish_branch: main
        cname: rules.abaplint.org
        force_orphan: true
        publish_dir: ./web/rules/build
