name: syntax.abaplint.org

on: [push, pull_request, workflow_dispatch]

jobs:
  syntax:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: npm run install
      run: npm run install
    - name: npm test
      run: npm test
    - name: npm run web.syntax
      run: npm run web.syntax
    - name: deploy syntax.abaplint.org
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' && github.repository == 'abaplint/abaplint'
      with:
        deploy_key: ${{ secrets.SYNTAX_DEPLOY_KEY }}
        external_repository: abaplint/syntax.abaplint.org
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        publish_branch: main
        cname: syntax.abaplint.org
        force_orphan: true
        publish_dir: ./web/syntax/build

